Fix dependencies 1651931699
bugout-dev/moonworm pull request #75
Opened 2022-05-07 14:14 UTC by zomglings

## Changes

Updated dependencies to not be so heavy.

- Created `moonworm[moonstream]` for the Moonstream DB-related dependencies
- Moved `web3[tester]` into `dev` dependencies.
- Top-level dependencies only include `web3` (with no lower bound)
- Removed `pysha3` dependency at top level (not sure why that was there in the first place)

## How to test these changes?

The tests were already failing before these changes. I tested code generation but not crawling.

We should fix the tests or remove the ones that don't matter. (Separate issue/PR)

## Related issues

2022-05-07 14:15 UTC, zomglings commented
I checked that the `mooncrawl` crawler on https://github.com/bugout-dev/moonstream pins the `moonworm` version to `0.1.11`. I am concerned that we may break dependencies elsewhere @Andrei-Dolgolev , @kompotkot .

In the future, in Moonstream crawlers, we should use `moonworm[moonstream]` as dependency, not just `moonworm`.

2022-05-09 09:39 UTC, Yhtiyar requested changes
I am gonna merge this only after I will add tests for crawling logic.

2022-05-09 09:39 UTC, Yhtiyar commented on setup.py
> +        "web3",
web3 >=5.27.0

2022-05-09 09:39 UTC, Yhtiyar commented on setup.py
> -        "pysha3<2.0.0,>=1.0.0",
pysha3 was necessary for something. (Not sure if it was on crawler side)

2022-05-09 09:39 UTC, Yhtiyar commented on setup.py
> -        "typing-extensions<4,>=3.7.4",
this one was also added for some reason. dunno remember.

2022-08-03 09:55 UTC, Yhtiyar commented
closing in favor of #83

2022-08-03 09:55 UTC, closed without merging